source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
inhibit_all_warnings!

target 'VePhonePublicDemo' do
  pod 'Toast'
  pod 'Masonry'
  pod 'SVProgressHUD'
  pod 'SDWebImage'
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
#  installer.generated_projects.each do |project|
#    project.targets.each do |target|
#      target.build_configurations.each do |config|
#        config.build_settings["CODE_SIGN_IDENTITY"] = "-"
#        config.build_settings["CODE_SIGN_ENTITLEMENTS"] = "-"
#        config.build_settings["CODE_SIGNING_ALLOWED"] = "NO"
#        config.build_settings["CODE_SIGNING_REQUIRED"] = "NO"
#      end
#    end
#  end
end
